### ISSUE TITLE
Hazelcast Kubernetes configuration

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8812]
I want to be able to configure HZ K8s plugin further. Now XP does not provide this option.

See this for reference: https://github.com/hazelcast/hazelcast-kubernetes/tree/v1.5.5

What I need to be able to set:

```yaml
hazelcast:
  network:
    join:
      kubernetes:
        enabled: true
        namespace: MY-KUBERNETES-NAMESPACE
        service-name: MY-SERVICE-NAME
        resolve-not-ready-addresses: true
```

Nice to have:

```yaml
hazelcast:
  network:
    join:
      kubernetes:
        service-label-name: ?
        service-label-value: ?
        pod-label-name: ?
        pod-label-value: ?
        use-node-name-as-external-address: true
        kubernetes-api-retries: 5

partition-group:
  enabled: true
  group-type: NODE_AWARE
```

Hardly useful, pretty much never set manually:

```yaml
hazelcast:
  network:
    join:
      kubernetes:
        kubernetes-master: ?
        api-token: ?
        ca-certificate: ?
        service-port: ?
```
